### PR TITLE
Streamable multipart attachments

### PR DESCRIPTION
**Pull request by stevebest**
This is all it takes, really!

Tests are soon to `{ follow: true }`.

### CODE REVIEW

**Comment by jo** [comment]
Awesome! The test can be similar to this one: https://github.com/dscape/nano/blob/master/tests/integration/multipart/insert.js#L57-L69

**Comment by jo** [comment]
@dscape All [ios targets fail](https://travis-ci.org/dscape/nano/builds/91817796) because of missing nvm. What can we do? I would suggest to just remove the os matrix.

**Comment by stevebest** [comment]
:hankey:, it seems like I trusted `request` too much. It [uses](https://github.com/request/request/blob/master/lib/multipart.js) outdated [combined-stream](https://github.com/felixge/node-combined-stream) module to build `multipart/related` requests.

Also, `request` switches to `Transfer-Encoding: chunked` as soon as it sees a stream in `mulitpart` array, whether a stream has a known 'length' or not. And I'm not sure if CouchDB even supports this encoding.

**Comment by jo** [comment]
Would it help if request would update its combined-stream dependency?

**Comment by stevebest** [comment]
Uuugh, it gets worse. [CouchDB silently hangs](https://issues.apache.org/jira/browse/COUCHDB-2295) on `Transfer-Encoding: chunked` requests, so the only option is to not use it -- at least until 1.7.

On the bright side, `request` allows specifying `multipart` option in the following form, which forces it to not use `chunked` encoding:

```js
request({
  method: 'PUT',
  uri: 'http://localhost:5984/mydb/mydoc',
  multipart: {
     chunked: false,   //  HUZZAH!!!
     data: [
       { content_type: 'application/json', length: 42, body: '{ ..., "_attachments": { "image.jpg": { ... } } }' },
       { content_type: 'image/jpg', length: 43234, body: fs.createReadStream('image.jpg') },
       /* etc */
     ]
  }
}, callback);
```

`nano` should probably use this form. But it won't help.

Support for streams in `request` [is broken anyways](https://github.com/request/request/blob/master/lib/multipart.js#L70-L72): when the encoding is not chunked, the stream gets wrapped in `Buffer`, which makes no sense at all.

So yeah, #299 would actually require changes in both `nano` _and_ `request`, and it's not that we just have to update dependencies.

**Comment by carlosduclos** [comment]
Hi,
The NanoJS repository has been merged into apache/couchdb-nano. Could you close this pull request and open it there instead?
Thanks in advance

**Comment by stevebest** [comment]
Closing because #299 is obsolete.

**Pull request closed without merging**
