### PR TITLE
Update request

### PR DESCRIPTION
**Pull request by jo**
From [`2.46.0`](https://github.com/request/request/blob/master/CHANGELOG.md#v2530-20150202) to [`2.53.0`](https://github.com/request/request/blob/master/CHANGELOG.md#v2470-20141026) with tons of improvements:

* Browserifyability (yeah!)
* Improved multipart handling
* Dependency updates

Just to mention some.

### CODE REVIEW

**Comment by dscape** [comment]
:+1:

**Comment by jo** [comment]
Browserify build is way too big if we don't do something:
```sh
[jo@jolap nano]$ browserify lib/nano.js --outfile nano.js
[jo@jolap nano]$ du -h nano.js 
1,5M	nano.js
```

**Comment by jo** [comment]
OK, I make `6.1.2` now

**Comment by dscape** [comment]
why is it 1.5m? cc @mikeal

**Comment by jo** [comment]
Oh, request itself browserifies to 1.4M:
```sh
[jo@jolap request]$ browserify request.js -o request-browser.js 
[jo@jolap request]$ du -h request-browser.js 
1,4M	request-browser.js
```
I must be doing something wrong.

**Pull request merged**
