### PR TITLE
Test with 4.2 (LTS) and 5.5 (Stable)

### PR DESCRIPTION
**Pull request by revington**
Test with 4.2 (LTS) and 5.5 (Stable)

### CODE REVIEW

**Comment by hellboy81** [comment]
Is nano still incompatible with 4.2.4 ?

**Comment by revington** [comment]
Tests pass with linux but they do not for OS X because that platform does not have node.js support.
From [travis docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs)
> Node.js builds are not available on the OSX environment.

**Comment by revington** [comment]
Should I remove OS X from the `os` section?
What is the point to test in OS X if node.js/OS X is not supported by travis?

**Comment by revington** [comment]
I have removed the OS X target since travis can not test node.js on OS X anyway.

**Comment by hellboy81** [comment]
Please accept merge request!

**Pull request merged**
